### PR TITLE
Fix excess responses on noisy WAN network 

### PR DESCRIPTION
**Pull request by brada4**
Fixes: https://github.com/openwrt/openwrt/issues/13340

In principle there is nothing forwarded from WAN unless some forward rule is present or it tries NAT traversal on recent new connection attempt. Past fixing excessive load generated in reported case also nat traversal will not need to retry socket connection, retransmitted SYN is likely to come when permitting rule/transient state is completely established.

 Signed-Off-By: `Andris PE <neandris..gmail.com>`

### CODE REVIEW

**Comment by jow-** [comment]
I could live with defaulting WAN-to-WAN forward to drop. The global inter-zone forward policy should stay at reject though.

**Comment by brada4** [comment]
OK, the global policy applies on new interfaces, but im fine with endangering unsuspecting.

**Comment by brada4** [comment]
Test case: connect wan to (10mbps) hub/repeater and watch spoofed traffic killing all communication there.

**Comment by brada4** [comment]
Sorry, wrong commit headings.

**Pull request closed without merging**
